workflow draft

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,6 +13,16 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
+      - name: verify tag matches version
+        run: |
+          # run generateb binary --version
+          BINARY_REPORTED_VERSION=v`cat Cargo.toml |grep ^version | head -n1 | cut -f 2 -d "\""`
+          echo "found version $BINARY_REPORTED_VERSION"
+          if [ "${{ github.event.release.tag_name }}" != "$BINARY_REPORTED_VERSION" ]; then
+            echo "Tag does not match version. Aborting"
+            exit 1
+          fi
+
       - name: Install Nxx
         uses: cachix/install-nix-action@v27
 
